import { AuthProvider } from "@/context/AuthContext";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { DM_Sans, Geist, Geist_Mono, Roboto } from "next/font/google";
import { ThemeProvider } from "../providers/themeProvider";
import "./globals.css";
import { NotificationProvider } from "@/context/NotificationContext";
import { TaskProvider } from "@/context/TaskContext";
import { ProjectProvider } from "@/context/ProjectContext";

const dmSansHeading = DM_Sans({
  subsets: ["latin"],
  variable: "--font-heading",
});

const roboto = Roboto({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        roboto.variable,
        dmSansHeading.variable,
      )}
    >
      <body className="min-h-screen flex flex-col">
        <AuthProvider>
          <ProjectProvider>
            <TaskProvider>
              <NotificationProvider>
                <ThemeProvider>{children}</ThemeProvider>
              </NotificationProvider>
            </TaskProvider>
          </ProjectProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
